services:

  db:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: quicktrack_homolog
      MYSQL_USER: quicktrack
      MYSQL_PASSWORD: quicktrack123

    volumes:
      - db_data_homolog:/var/lib/mysql

    ports:
      - "127.0.0.1:3307:3306"

    networks:
      - qt-network

  backend:
    build: ./backend
    restart: always

    env_file:
      - .env

    volumes:
      - ./media:/media

    depends_on:
      - db

    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

    ports:
      - "8001:8000"

    networks:
      - qt-network

networks:
  qt-network:

volumes:
  db_data_homolog:
