# Generated by Django 4.2.27 on 2026-03-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifesto', '0033_baixanf_ia_ocr_status_baixanf_ia_yolo_status'),
        ('usuarios', '0009_alter_motorista_tipo_usuario_precadastrosac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ENDERECO', 'Endereço não corresponde'), ('MERCADORIA', 'Problemas com a mercadoria / Avaria'), ('CLIENTE_AUSENTE', 'Cliente ausente / Local fechado'), ('VEICULO', 'Problemas no veículo / Acidente'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Categoria do Chamado')),
                ('status', models.CharField(choices=[('CANAL_ABERTO', 'Aberto (Aguardando Atendimento)'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('RESOLVIDO', 'Resolvido')], default='CANAL_ABERTO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado Em')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendente (SAC)')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_suporte', to='usuarios.filial', verbose_name='Filial')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_suporte', to='usuarios.motorista', verbose_name='Motorista')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_suporte', to='manifesto.notafiscal', verbose_name='Nota Fiscal Relacionada')),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_por_motorista', models.BooleanField(default=True, verbose_name='Enviado pelo Motorista?')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('AUDIO', 'Áudio'), ('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('SISTEMA', 'Mensagem do Sistema')], default='TEXTO', max_length=20, verbose_name='Tipo de Mensagem')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Conteúdo em Texto')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='suporte/anexos/', verbose_name='Arquivo Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada Em')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida?')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por (Atendente)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='suporte.ticketsuporte', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Mensagem do Suporte',
                'verbose_name_plural': 'Mensagens do Suporte',
                'ordering': ['created_at'],
            },
        ),
    ]
