# Generated by Django 4.2.27 on 2026-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsuporte',
            name='categoria',
            field=models.CharField(choices=[('DUVIDA_NF', 'Dúvida sobre Nota Fiscal'), ('PROBLEMA_ENDERECO', 'Problema no Endereço / Telefone Errado'), ('PROBLEMA_APP', 'Problema no Aplicativo'), ('AVARIA_CARGA', 'Avaria na Carga / Acidente'), ('AGUARDE_RETORNO', 'Preciso de liberação / Aguardo retorno'), ('OUTROS', 'Outro Motivo')], max_length=50, verbose_name='Categoria do Chamado'),
        ),
    ]
