# Generated by Django 4.2.29 on 2026-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0002_alter_ticketsuporte_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsuporte',
            name='status',
            field=models.CharField(choices=[('CANAL_ABERTO', 'Aberto (Aguardando Atendimento)'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='CANAL_ABERTO', max_length=20, verbose_name='Status'),
        ),
    ]
