# Generated by Django 4.2.30 on 2026-07-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0004_videotreinamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTreinamento',
        ),
    ]
