# Generated by Django 4.2.30 on 2026-04-28 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBaixaSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('freight_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Frete (Minuta)')),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota / Minuta')),
                ('ocorrencia_codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cód. Ocorrência')),
                ('somente_comprovante', models.BooleanField(default=False, verbose_name='Somente Comprovante?')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('url_foto_original', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Foto Original')),
                ('url_foto_recortada', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Foto Recortada (IA)')),
                ('ia_yolo_status', models.BooleanField(default=False, verbose_name='Processado na IA?')),
                ('status_tms', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso (TMS)'), ('ERRO', 'Erro (TMS)')], default='PENDENTE', max_length=20, verbose_name='Status Integração')),
                ('log_erro_tms', models.TextField(blank=True, null=True, verbose_name='Log de Erro (TMS)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Baixa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador do SAC')),
            ],
            options={
                'verbose_name': 'Histórico de Baixa (SAC)',
                'verbose_name_plural': 'Histórico de Baixas (SAC)',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
