# Generated by Django 5.1.4 on 2026-07-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac_mobile', '0001_initial'),
        ('usuarios', '0022_filial_horario_rebusca_esl'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRebuscaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], max_length=15)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=15)),
                ('detalhes_manifestos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_rebusca', to='usuarios.filial')),
            ],
            options={
                'verbose_name': 'Log de Rebusca (Filial)',
                'verbose_name_plural': 'Logs de Rebusca (Filiais)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
