# Generated by Django 5.1.4 on 2026-07-14 15:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifesto', '0039_logbaixanfe'),
        ('usuarios', '0020_alter_devicetoken_id_alter_devicetoken_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('evolution_api', 'Evolution API'), ('z_api', 'Z-API'), ('wppconnect', 'WPPConnect'), ('codechat', 'CodeChat')], max_length=30, unique=True, verbose_name='Provedor')),
                ('url_base', models.URLField(help_text='URL base do servidor (ex: https://evo.seudominio.com.br)', verbose_name='URL do Servidor')),
                ('api_key', models.CharField(help_text='Token de autenticação global do servidor', max_length=200, verbose_name='API Key / Token Global')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar este provedor imediatamente. O sistema passará a usar o próximo na fila.', verbose_name='✅ Ativo')),
                ('prioridade', models.IntegerField(default=0, help_text='Menor número = maior prioridade. Se o provedor principal cair, o próximo assume.', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Provedor WhatsApp',
                'verbose_name_plural': 'Provedores WhatsApp',
                'ordering': ['prioridade'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(help_text='Nome cadastrado na Evolution/Z-API (ex: filial_sp, bot_rj)', max_length=100, verbose_name='Nome da Instância')),
                ('api_token', models.CharField(blank=True, help_text='Se preenchido, usa este token específico em vez da API Key Global do provedor.', max_length=200, null=True, verbose_name='Token da Instância (Opcional)')),
                ('numero_whatsapp', models.CharField(help_text='Formato internacional: 5511999999999', max_length=20, verbose_name='Número WhatsApp')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para pausar envios desta filial', verbose_name='✅ Instância Ativa')),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instancia_whatsapp', to='usuarios.filial', verbose_name='Filial')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='whatsbot.whatsappprovedor', verbose_name='Provedor de Envio')),
            ],
            options={
                'verbose_name': 'Instância WhatsApp (Filial)',
                'verbose_name_plural': 'Instâncias WhatsApp (Filiais)',
            },
        ),
        migrations.CreateModel(
            name='ManifestoBotCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('payload_tms', models.JSONField(default=list, help_text='Resposta completa da API do TMS para auditoria', verbose_name='JSON Bruto do TMS')),
                ('manifestos_encontrados', models.JSONField(default=list, help_text='Lista de números de manifesto retornados pelo TMS', verbose_name='Manifestos Encontrados')),
                ('total_manifestos', models.IntegerField(default=0, verbose_name='Total de Manifestos')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_cache', to='usuarios.filial')),
            ],
            options={
                'verbose_name': 'Cache de Manifestos (Bot)',
                'verbose_name_plural': 'Cache de Manifestos (Bot)',
                'unique_together': {('filial', 'data_referencia')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoManifestoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manifesto_tms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número MFT TMS')),
                ('data_referencia', models.DateField(default=datetime.date.today, verbose_name='Data de Referência')),
                ('rodada', models.IntegerField(help_text='1=11h, 2=12h, 3=14h, 4=15h, 5=16h', verbose_name='Rodada do Dia')),
                ('tipo_mensagem', models.CharField(choices=[('ATIVACAO', 'Lembrete de Ativação'), ('PENDENCIA', 'Manifesto Anterior Pendente')], max_length=20)),
                ('mensagem_enviada', models.TextField(verbose_name='Mensagem Enviada')),
                ('provedor_usado', models.CharField(max_length=30, verbose_name='Provedor Utilizado')),
                ('instancia_usada', models.CharField(max_length=100, verbose_name='Instância Utilizada')),
                ('numero_destino', models.CharField(max_length=20, verbose_name='Número de Destino')),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado com Sucesso'), ('ERRO', 'Erro no Envio'), ('SEM_TELEFONE', 'Motorista Sem Telefone')], default='ENVIADO', max_length=20)),
                ('erro_detalhe', models.TextField(blank=True, null=True, verbose_name='Detalhe do Erro')),
                ('resposta_api', models.JSONField(blank=True, null=True, verbose_name='Resposta da API')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_bot', to='usuarios.filial')),
                ('manifesto', models.ForeignKey(blank=True, help_text='Opcional. Preenchido apenas se o manifesto já existir no banco local.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_bot', to='manifesto.manifesto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_bot', to='usuarios.motorista')),
            ],
            options={
                'verbose_name': 'Log de Notificação (Bot)',
                'verbose_name_plural': 'Logs de Notificações (Bot)',
                'ordering': ['-enviado_em'],
                'unique_together': {('motorista', 'numero_manifesto_tms', 'rodada', 'data_referencia')},
            },
        ),
    ]
