# Generated by Django 4.2.30 on 2026-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstancia',
            name='api_token',
            field=models.CharField(blank=True, help_text='Se preenchido, usa este token específico em vez da API Key Global do provedor.', max_length=200, null=True, verbose_name='Token da Instância (Opcional)'),
        ),
    ]
