# Generated by Django 4.2.30 on 2026-07-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0039_merge_20260619_1029'),
        ('usuarios', '0016_merge_20260615_1752'),
        ('whatsbot', '0002_whatsappinstancia_api_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificacaomanifestolog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificacaomanifestolog',
            name='numero_manifesto_tms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número MFT TMS'),
        ),
        migrations.AlterField(
            model_name='notificacaomanifestolog',
            name='manifesto',
            field=models.ForeignKey(blank=True, help_text='Opcional. Preenchido apenas se o manifesto já existir no banco local.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_bot', to='manifesto.manifesto'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacaomanifestolog',
            unique_together={('motorista', 'numero_manifesto_tms', 'rodada', 'data_referencia')},
        ),
    ]
