# Generated by Django 5.1.4 on 2026-07-21 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0022_filial_horario_rebusca_esl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraClassificacaoErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'Manifesto em trânsito', 'Ocorrência duplicada'", max_length=100, verbose_name='Nome da Regra')),
                ('pattern', models.CharField(help_text="Trecho de texto que deve aparecer na mensagem de erro. Case-insensitive. Ex: 'manifesto em trânsito'", max_length=255, verbose_name='Texto para buscar')),
                ('usar_regex', models.BooleanField(default=False, help_text='Se marcado, o pattern é interpretado como expressão regular', verbose_name='Usar Regex?')),
                ('severidade', models.CharField(choices=[('CRITICO', 'Crítico'), ('ATENCAO', 'Atenção'), ('INFO', 'Informação')], default='ATENCAO', max_length=10)),
                ('publico_alvo', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('SAC', 'SAC / Suporte'), ('AMBOS', 'Ambos')], default='AMBOS', help_text='Define quem vê este tipo de erro na torre', max_length=15, verbose_name='Público-alvo')),
                ('exibir_torre', models.BooleanField(default=True, help_text='Se desmarcado, o erro é logado mas NÃO aparece na torre de controle', verbose_name='Exibir na Torre?')),
                ('prioridade', models.IntegerField(default=100, help_text='Menor número = maior prioridade. A primeira regra que bater é usada.', verbose_name='Prioridade')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regra de Classificação de Erro',
                'verbose_name_plural': 'Regras de Classificação de Erros',
                'ordering': ['prioridade'],
            },
        ),
        migrations.CreateModel(
            name='LogErroOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('INTEGRACAO_BAIXA', 'Integração de Baixa (NF-e)'), ('INTEGRACAO_COLETA', 'Integração de Coleta'), ('INTEGRACAO_MINUTA', 'Integração de Minuta'), ('FINALIZACAO_MANIFESTO', 'Finalização de Manifesto'), ('SINCRONIZACAO_NFE', 'Sincronização de NF-e'), ('WEBHOOK_MANIFESTO', 'Webhook de Manifesto'), ('BUSCA_MANIFESTO', 'Busca/Importação de Manifesto'), ('ERRO_MOTORISTA', 'Erro do Motorista'), ('OUTRO', 'Outro')], max_length=30)),
                ('severidade', models.CharField(choices=[('CRITICO', 'Crítico'), ('ATENCAO', 'Atenção'), ('INFO', 'Informação')], default='ATENCAO', max_length=10)),
                ('publico_alvo', models.CharField(default='AMBOS', help_text='Herdado da regra de classificação', max_length=15)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('erro_raw', models.TextField(blank=True, help_text='Texto completo retornado pelo TMS para auditoria', null=True, verbose_name='Mensagem de erro original')),
                ('manifesto_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('motorista_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido (Manual)'), ('AUTO_RESOLVIDO', 'Resolvido (Automático)'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=15)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('resolucao_automatica', models.BooleanField(default=False, help_text='Indica se o erro foi resolvido automaticamente por uma retentativa bem-sucedida')),
                ('observacao_resolucao', models.TextField(blank=True, help_text='Anotação opcional do operador', null=True, verbose_name='Observação da Resolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros_operacionais', to='usuarios.filial')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('regra_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.regraclassificacaoerro', verbose_name='Regra que classificou')),
            ],
            options={
                'verbose_name': 'Log de Erro Operacional',
                'verbose_name_plural': 'Logs de Erros Operacionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['filial', 'status', '-criado_em'], name='operacional_filial__9deea1_idx'), models.Index(fields=['severidade', 'status'], name='operacional_severid_7921b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TutorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(help_text="Ex: 'torre_erros', 'dashboard', 'manifestos'", max_length=100, verbose_name='Identificador da Página')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutorial do Usuário',
                'verbose_name_plural': 'Tutoriais dos Usuários',
                'unique_together': {('usuario', 'pagina')},
            },
        ),
    ]
