# Generated by Django 4.2.30 on 2026-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerrooperacional',
            name='observacao_resolucao',
            field=models.TextField(blank=True, help_text='Anotação opcional do operador', null=True, verbose_name='Observação da Resolução'),
        ),
        migrations.AddField(
            model_name='logerrooperacional',
            name='resolucao_automatica',
            field=models.BooleanField(default=False, help_text='Indica se o erro foi resolvido automaticamente por uma retentativa bem-sucedida'),
        ),
        migrations.AlterField(
            model_name='logerrooperacional',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido (Manual)'), ('AUTO_RESOLVIDO', 'Resolvido (Automático)'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=15),
        ),
    ]
