# Generated by Django 5.1.4 on 2026-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerrooperacional',
            name='historico_tentativas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de datas/horas de cada ocorrência', verbose_name='Histórico de Tentativas'),
        ),
        migrations.AddField(
            model_name='logerrooperacional',
            name='qtd_tentativas',
            field=models.IntegerField(default=1, help_text='Quantidade de vezes que este exato erro ocorreu', verbose_name='Qtd de Tentativas'),
        ),
    ]
