# Generated by Django 5.1.4 on 2026-08-05 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(help_text="Ex: 'torre_erros', 'dashboard', 'manifestos'", max_length=100, verbose_name='Identificador da Página')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutorial do Usuário',
                'verbose_name_plural': 'Tutoriais dos Usuários',
                'unique_together': {('usuario', 'pagina')},
            },
        ),
    ]
