# Generated by Django 5.1.4 on 2026-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_logerrooperacional_historico_tentativas_and_more'),
        ('operacional', '0003_tutorialusuario'),
    ]

    operations = [
    ]
