# Generated by Django 5.1.4 on 2026-08-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_logerrooperacional_observacao_resolucao_and_more'),
        ('operacional', '0004_merge_20260805'),
    ]

    operations = [
    ]
