# Generated by Django 5.1.4 on 2026-09-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('user', models.OneToOneField(blank=True, help_text='Vinculado ao auth.User para autenticação via sessão.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Conta de Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Cliente',
                'verbose_name_plural': 'Usuários Clientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='VinculoPagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagador_nome', models.CharField(help_text='Deve corresponder exatamente ao Frete.pagador_nome no sistema.', max_length=255, verbose_name='Nome do Pagador')),
                ('pagador_documento', models.CharField(blank=True, help_text='CNPJ para referência visual. O match principal é pelo nome.', max_length=50, null=True, verbose_name='CNPJ do Pagador')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='clientes.usuariocliente', verbose_name='Usuário Cliente')),
            ],
            options={
                'verbose_name': 'Vínculo de Pagador',
                'verbose_name_plural': 'Vínculos de Pagadores',
                'ordering': ['pagador_nome'],
                'unique_together': {('usuario_cliente', 'pagador_nome')},
            },
        ),
    ]
