# Generated by Django 4.2.27 on 2025-12-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manifesto', models.CharField(max_length=50, unique=True, verbose_name='Número do Manifesto')),
                ('km_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('km_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_ativos', to='usuarios.motorista', verbose_name='Motorista Atribuído')),
            ],
            options={
                'verbose_name': 'Manifesto',
                'verbose_name_plural': 'Manifestos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tms', models.CharField(max_length=10, unique=True, verbose_name='Código TMS')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega/Coleta (Sucesso)'), ('PROBLEMA', 'Problema (Rejeição/Não Realizada)')], default='PROBLEMA', max_length=10)),
            ],
            options={
                'verbose_name': 'Código de Ocorrência',
                'verbose_name_plural': 'Códigos de Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='Número NF')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatário')),
                ('endereco_entrega', models.CharField(max_length=255, verbose_name='Endereço de Entrega')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('BAIXADA', 'Baixada/Entregue'), ('OCORRENCIA', 'Ocorrência Registrada')], default='PENDENTE', max_length=20)),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='manifesto.manifesto')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='HistoricoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tms', models.CharField(max_length=10, verbose_name='Código Ocorrência TMS')),
                ('data_ocorrencia', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('manifesto_evento', models.CharField(max_length=50, verbose_name='Cód. do Manifesto do Evento')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='manifesto.notafiscal')),
            ],
            options={
                'verbose_name': 'Histórico de Ocorrência',
                'verbose_name_plural': 'Históricos de Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='BaixaNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega/Coleta'), ('OCORRENCIA', 'Ocorrência')], max_length=10)),
                ('comprovante_foto', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_baixa', models.DateTimeField(auto_now_add=True)),
                ('nota_fiscal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baixa_info', to='manifesto.notafiscal')),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manifesto.ocorrencia')),
            ],
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['chave_acesso'], name='manifesto_n_chave_a_f3dbbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('manifesto', 'chave_acesso')},
        ),
        migrations.AddIndex(
            model_name='historicoocorrencia',
            index=models.Index(fields=['data_ocorrencia'], name='manifesto_h_data_oc_0e3c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicoocorrencia',
            unique_together={('nota_fiscal', 'codigo_tms', 'data_ocorrencia')},
        ),
    ]
