# Generated by Django 4.2.27 on 2025-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Início (Buscado, mas não iniciado)'), ('TRANSPORTE', 'Em Transporte (Rota iniciada)'), ('FINALIZADO', 'Finalizado (Com KM Final registrado)'), ('CANCELADO', 'Cancelado (Pelo operacional)')], default='AGUARDANDO', max_length=20, verbose_name='Status do Manifesto'),
        ),
    ]
