# Generated by Django 4.2.27 on 2025-12-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_motorista_user'),
        ('manifesto', '0002_manifesto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestoBuscaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manifesto', models.CharField(max_length=50, unique=True)),
                ('dados', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Processamento'), ('PROCESSADO', 'Prévia Disponível'), ('FALHA', 'Falha no Processamento'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas_manifesto', to='usuarios.motorista')),
            ],
            options={
                'verbose_name': 'Busca de Manifesto',
                'verbose_name_plural': 'Buscas de Manifestos',
            },
        ),
    ]
