# Generated by Django 4.2.27 on 2025-12-15 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_motorista_user'),
        ('manifesto', '0003_manifestobuscalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestobuscalog',
            name='dados',
        ),
        migrations.RemoveField(
            model_name='manifestobuscalog',
            name='data_ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='manifestobuscalog',
            name='mensagem_erro',
        ),
        migrations.AddField(
            model_name='manifestobuscalog',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestobuscalog',
            name='payload',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestobuscalog',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.motorista'),
        ),
        migrations.AlterField(
            model_name='manifestobuscalog',
            name='numero_manifesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manifestobuscalog',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], default='AGUARDANDO', max_length=20),
        ),
    ]
