# Generated by Django 4.2.27 on 2025-12-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0004_remove_manifestobuscalog_dados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='status',
            field=models.CharField(choices=[('TRANSPORTE', 'Em Transporte (Rota iniciada)'), ('FINALIZADO', 'Finalizado (Com KM Final registrado)'), ('CANCELADO', 'Cancelado (Pelo operacional)')], default='AGUARDANDO', max_length=20, verbose_name='Status do Manifesto'),
        ),
    ]
