# Generated by Django 4.2.27 on 2025-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0005_alter_manifesto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestobuscalog',
            name='mensagem_erro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
