# Generated by Django 4.2.27 on 2025-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_motorista_user'),
        ('manifesto', '0006_manifestobuscalog_mensagem_erro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='usuarios.motorista', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='status',
            field=models.CharField(choices=[('EM_TRANSPORTE', 'Em Transporte'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_TRANSPORTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='manifestobuscalog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestobuscalog',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('PRONTO_PREVIEW', 'Pronto para Preview'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='manifestobuscalog',
            unique_together={('numero_manifesto', 'motorista')},
        ),
        migrations.AddConstraint(
            model_name='manifesto',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EM_TRANSPORTE')), fields=('motorista',), name='um_manifesto_em_transporte_por_motorista'),
        ),
    ]
