# Generated by Django 4.2.27 on 2025-12-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0007_alter_manifesto_motorista_alter_manifesto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='documento_recebedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='recebedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
