# Generated by Django 4.2.27 on 2025-12-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0008_baixanf_documento_recebedor_baixanf_recebedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
