# Generated by Django 4.2.27 on 2025-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0009_baixanf_latitude_baixanf_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='data_integracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='log_erro_tms',
            field=models.TextField(blank=True, null=True, verbose_name='Log de Erro ESL'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='processado_tms',
            field=models.BooleanField(default=False, verbose_name='Integrado com ESL'),
        ),
    ]
