# Generated by Django 4.2.27 on 2025-12-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0010_baixanf_data_integracao_baixanf_log_erro_tms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baixanf',
            options={'verbose_name': 'Nota Fiscal Baixada', 'verbose_name_plural': 'Notas Fiscais Baixadas'},
        ),
    ]
