# Generated by Django 4.2.27 on 2026-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0011_alter_baixanf_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='integrado_tms',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Integrado ESL'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave de Acesso'),
        ),
    ]
