# Generated by Django 4.2.27 on 2026-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0012_alter_notafiscal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='comprovante_foto_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
