# Generated by Django 4.2.27 on 2026-01-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0013_baixanf_comprovante_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixanf',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixa_info', to='manifesto.notafiscal'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso'),
        ),
    ]
