# Generated by Django 4.2.27 on 2026-01-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_filial'),
        ('manifesto', '0014_alter_baixanf_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='usuarios.filial', verbose_name='Filial'),
        ),
    ]
