# Generated by Django 4.2.27 on 2026-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0015_manifesto_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventoManifestoESL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='ESL', max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
