# Generated by Django 4.2.27 on 2026-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0016_webhookeventomanifestoesl'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookeventomanifestoesl',
            name='numero_manifesto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
