# Generated by Django 4.2.27 on 2026-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0017_webhookeventomanifestoesl_numero_manifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='qtd_despacho',
            field=models.IntegerField(default=0, verbose_name='Qtd Despacho'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='qtd_entrega',
            field=models.IntegerField(default=0, verbose_name='Qtd Entrega'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='qtd_retirada',
            field=models.IntegerField(default=0, verbose_name='Qtd Retirada'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='qtd_transferencia',
            field=models.IntegerField(default=0, verbose_name='Qtd Transferência'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tipo_operacao',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('DESPACHO', 'Despacho'), ('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada'), ('OUTROS', 'Outros')], default='ENTREGA', max_length=20),
        ),
    ]
