# Generated by Django 4.2.27 on 2026-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0018_manifesto_qtd_despacho_manifesto_qtd_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='manifesto_id_tms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
