# Generated by Django 4.2.28 on 2026-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0019_manifesto_manifesto_id_tms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='tipo_operacao',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferência'), ('DESPACHO', 'Despacho'), ('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada'), ('OUTROS', 'Outros')], default='ENTREGA', max_length=20, null=True),
        ),
    ]
