# Generated by Django 4.2.28 on 2026-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0020_alter_notafiscal_tipo_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='qtd_despacho',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qtd Despacho'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='qtd_entrega',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qtd Entrega'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='qtd_retirada',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qtd Retirada'),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='qtd_transferencia',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qtd Transferência'),
        ),
    ]
