# Generated by Django 4.2.28 on 2026-02-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0021_alter_manifesto_qtd_despacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='freight_id_tms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
