# Generated by Django 4.2.28 on 2026-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0022_notafiscal_freight_id_tms'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='payload_enviado',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON enviado para ESL'),
        ),
    ]
