# Generated by Django 4.2.29 on 2026-03-10 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0023_baixanf_payload_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixanf',
            name='data_baixa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
