# Generated by Django 4.2.27 on 2026-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0024_alter_baixanf_data_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestobuscalog',
            name='quantidade_notas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Notas'),
        ),
    ]
