# Generated by Django 4.2.27 on 2026-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0025_manifestobuscalog_quantidade_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestobuscalog',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
