# Generated by Django 4.2.29 on 2026-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0026_manifestobuscalog_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='ultima_bateria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Última Bateria (%)'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='ultima_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Última Latitude'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='ultima_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Última Longitude'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='ultima_rede',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Rede'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso'),
        ),
    ]
