# Generated by Django 4.2.29 on 2026-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0027_manifesto_ultima_bateria_manifesto_ultima_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='chave_cte',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave do CT-e'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='numero_coleta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Coleta'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='numero_cte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do CT-e'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='tipo_operacao',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferência'), ('DESPACHO', 'Despacho'), ('ENTREGA', 'Entrega'), ('COLETA', 'Coleta'), ('RETIRADA', 'Retirada'), ('OUTROS', 'Outros')], default='ENTREGA', max_length=20, null=True),
        ),
    ]
