# Generated by Django 4.2.29 on 2026-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0028_notafiscal_chave_cte_notafiscal_numero_coleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_TRANSPORTE', 'Em Transporte'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_TRANSPORTE', max_length=20),
        ),
    ]
