# Generated by Django 4.2.29 on 2026-03-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manifesto', '0029_alter_manifesto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTokenControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_mensal', models.IntegerField(default=5000, verbose_name='Limite do Plano')),
                ('total_mes_atual', models.IntegerField(default=0, verbose_name='Consumido no Mês')),
                ('mes_referencia', models.DateField(default=django.utils.timezone.now, verbose_name='Mês de Referência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Token Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle de Token Webhook',
                'verbose_name_plural': 'Controle de Tokens Webhook',
            },
        ),
    ]
