# Generated by Django 4.2.29 on 2026-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0030_webhooktokencontrol'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['numero_nota'], name='manifesto_n_numero__f51c64_idx'),
        ),
    ]
