# Generated by Django 4.2.27 on 2026-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0031_notafiscal_manifesto_n_numero__f51c64_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='comprovante_original_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
