# Generated by Django 4.2.27 on 2026-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0032_baixanf_comprovante_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='ia_ocr_status',
            field=models.BooleanField(default=False, verbose_name='OCR: Leitura Realizada'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='ia_yolo_status',
            field=models.BooleanField(default=False, verbose_name='YOLO: Canhoto Detectado'),
        ),
    ]
