# Generated by Django 4.2.30 on 2026-04-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_motorista_is_sac_mobile'),
        ('manifesto', '0033_baixanf_ia_ocr_status_baixanf_ia_yolo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='autor_baixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_realizadas', to='usuarios.motorista', verbose_name='Autor da Baixa'),
        ),
    ]
