# Generated by Django 4.2.30 on 2026-04-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0034_baixanf_autor_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='motivo_baixa',
            field=models.CharField(choices=[('APP_ERROR', 'Erro de Aplicativo/Hardware'), ('MOTORISTA_DESLEIXO', 'Não Finalizado pelo Motorista (Penalidade)'), ('OPERACAO_NORMAL', 'Operação Normal (Motorista)')], default='OPERACAO_NORMAL', max_length=50, verbose_name='Motivo da Baixa (Auditoria)'),
        ),
    ]
