# Generated by Django 5.1.4 on 2026-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0035_baixanf_motivo_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='is_coleta',
            field=models.BooleanField(default=False, help_text='Marque se esta ocorrência deve aparecer nas opções do aplicativo para recusa de coletas.', verbose_name='Exibir em Coletas'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='is_entrega',
            field=models.BooleanField(default=False, help_text='Marque se esta ocorrência deve aparecer nas opções do aplicativo para problemas de entrega (NÃO ENTREGA).', verbose_name='Exibir em Entregas'),
        ),
    ]
