# Generated by Django 4.2.30 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0035_baixanf_motivo_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='is_coleta',
            field=models.BooleanField(default=False, help_text='Marque se esta ocorrência deve aparecer nas opções do aplicativo para recusa de coletas.', verbose_name='Exibir em Coletas'),
        ),
    ]
