# Generated by Django 4.2.30 on 2026-06-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0036_ocorrencia_is_coleta_ocorrencia_is_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='codigo_referencia',
            field=models.CharField(blank=True, help_text="Código fixo padrão enviado pelo aplicativo (ex: '01' para entrega de sucesso).", max_length=20, null=True, verbose_name='Código de Referência do App'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo_tms',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código TMS'),
        ),
    ]
