# Generated by Django 4.2.30 on 2026-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0036_ocorrencia_is_coleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='is_entrega',
            field=models.BooleanField(default=False, help_text='Marque se esta ocorrência deve aparecer nas opções do aplicativo para problemas de entrega (NÃO ENTREGA).', verbose_name='Exibir em Entregas'),
        ),
    ]
