# Generated by Django 4.2.30 on 2026-06-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0036_ocorrencia_is_coleta_ocorrencia_is_entrega'),
        ('manifesto', '0037_ocorrencia_is_entrega'),
    ]

    operations = [
    ]
