# Generated by Django 4.1 on 2026-07-07 10:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0037_ocorrencia_codigo_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventoSOAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manifesto', models.CharField(max_length=50)),
                ('payload_xml', models.TextField()),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
