# Generated by Django on 2026-06-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0038_webhookeventosoap'),
    ]

    operations = [
    ]
