# Generated by Django 4.2.30 on 2026-06-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0037_ocorrencia_codigo_referencia_and_more'),
        ('manifesto', '0038_merge_20260615_1752'),
    ]

    operations = [
    ]
