# Generated by Django 5.1.4 on 2026-07-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0038_webhookeventosoap'),
        ('usuarios', '0020_alter_devicetoken_id_alter_devicetoken_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBaixaNfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto_numero', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº Manifesto')),
                ('numero_nota', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº Nota Fiscal')),
                ('tipo', models.CharField(choices=[('BAIXA_SUCESSO', 'Baixa Realizada com Sucesso'), ('BAIXA_ERRO', 'Erro na Baixa'), ('INTEGRACAO_SUCESSO', 'Integração TMS com Sucesso'), ('INTEGRACAO_ERRO', 'Erro na Integração TMS'), ('IMPORTACAO_ERRO', 'Erro na Importação de Manifesto')], max_length=30, verbose_name='Tipo do Evento')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='Mensagem/Detalhes')),
                ('lido', models.BooleanField(default=False, verbose_name='Notificação Lida')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_baixa_nfe', to='usuarios.filial', verbose_name='Filial')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_baixa', to='manifesto.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Log de Baixa NF-e',
                'verbose_name_plural': 'Logs de Baixa NF-e',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='manifesto_l_criado__88676d_idx'), models.Index(fields=['lido', 'tipo'], name='manifesto_l_lido_7af873_idx')],
            },
        ),
    ]
