# Generated by Django 5.1.4 on 2026-07-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0039_logbaixanfe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_id_tms', models.CharField(max_length=50, unique=True, verbose_name='ID do Frete na ESL (sequence_code)')),
                ('numero_cte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do CT-e')),
                ('chave_cte', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave do CT-e')),
                ('modal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modal')),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_taxado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('remetente', models.CharField(blank=True, max_length=255, null=True)),
                ('pagador_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('pagador_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('natureza_carga', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frete/CT-e',
                'verbose_name_plural': 'Fretes/CT-es',
            },
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='frete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='manifesto.frete'),
        ),
    ]
