# Generated by Django 4.2.30 on 2026-07-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0039_logbaixanfe'),
        ('manifesto', '0039_merge_20260619_1029'),
    ]

    operations = [
    ]
