# Generated by Django 4.2.30 on 2026-07-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0040_frete_notafiscal_frete'),
        ('manifesto', '0040_merge_0039_logbaixanfe_0039_merge_20260619_1029'),
    ]

    operations = [
    ]
