# Generated by Django on 2026-07-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0040_frete_notafiscal_frete'),
    ]

    operations = [
    ]
