# Generated by Django 5.1.4 on 2026-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0041_merge_20260721_1522'),
        ('manifesto', '0040_merge_0039_logbaixanfe_0039_merge_20260619_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP de Entrega'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude do Destino'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude do Destino'),
        ),
    ]
