# Generated by Django 5.1.4 on 2026-08-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0042_notafiscal_cep_notafiscal_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('CAVALO', 'Cavalo Mecânico'), ('CARRETA', 'Carreta'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('UTILITARIO', 'Utilitário'), ('OUTRO', 'Outro')], default='CAVALO', max_length=15, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.AddField(
            model_name='manifesto',
            name='status_tms',
            field=models.CharField(choices=[('pending', 'Pendente no TMS'), ('in_transit', 'Em Trânsito no TMS'), ('closed', 'Finalizado no TMS')], default='in_transit', max_length=20, verbose_name='Status no TMS'),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_veiculo', to='manifesto.veiculo', verbose_name='Veículo'),
        ),
    ]
