# Generated by Django 5.1.4 on 2026-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0043_veiculo_manifesto_status_tms_manifesto_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixanf',
            name='motivo_rejeicao_ia',
            field=models.CharField(blank=True, choices=[('BLUR_DESFOCADO', 'Foto Desfocada / Embaçada'), ('OCR_ILEGIVEL', 'Texto ou Dados Ilegíveis'), ('SEM_CANHOTO', 'Canhoto Não Identificado')], max_length=50, null=True, verbose_name='Motivo de Rejeição IA'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='qualidade_canhoto',
            field=models.CharField(choices=[('PENDENTE_ANALISE', 'Pendente de Análise'), ('APROVADO', 'Aprovado pela IA'), ('ILEGIVEL', 'Ilegível / Fora de Foco'), ('REPROVADO_LIMITE_3X', 'Reprovado após 3 Tentativas'), ('APROVADO_MANUAL', 'Aprovado Manualmente pelo SAC')], default='PENDENTE_ANALISE', max_length=30, verbose_name='Qualidade do Canhoto'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='score_nitidez',
            field=models.FloatField(blank=True, null=True, verbose_name='Score de Nitidez (OpenCV)'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='solicitar_nova_foto',
            field=models.BooleanField(default=False, verbose_name='Solicitar Nova Foto ao Motorista'),
        ),
        migrations.AddField(
            model_name='baixanf',
            name='tentativa_foto',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tentativa da Foto'),
        ),
    ]
