# Generated by Django 5.1.4 on 2026-08-31 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0044_baixanf_motivo_rejeicao_ia_baixanf_qualidade_canhoto_and_more'),
        ('usuarios', '0029_add_tipo_operacao_confirmado_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='filial_operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_operacao', to='usuarios.filial', verbose_name='Filial de Operação (Base)'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tipo_operacao_confirmado_webhook',
            field=models.BooleanField(default=False, verbose_name='Tipo confirmado via Webhook'),
        ),
    ]
