# Generated by Django 5.1.4 on 2026-09-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0045_add_tipo_operacao_confirmado_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogChecklistManifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_manifesto', models.CharField(max_length=50, verbose_name='Nº Manifesto')),
                ('evento', models.CharField(max_length=30, verbose_name='Evento (Status)')),
                ('status_envio', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('AVISO', 'Aviso / Resposta Inesperada')], default='SUCESSO', max_length=20, verbose_name='Status do Envio')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('payload_enviado', models.JSONField(blank=True, null=True, verbose_name='Payload Enviado')),
                ('resposta_api', models.TextField(blank=True, default='', verbose_name='Resposta da API')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Envio')),
                ('manifesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_checklist', to='manifesto.manifesto', verbose_name='Manifesto')),
            ],
            options={
                'verbose_name': 'Log de Envio Checklist (QVX)',
                'verbose_name_plural': 'Logs de Envio Checklist (QVX)',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='manifesto_l_criado__881970_idx'), models.Index(fields=['numero_manifesto'], name='manifesto_l_numero__1655c9_idx'), models.Index(fields=['status_envio'], name='manifesto_l_status__c9cefa_idx')],
            },
        ),
    ]
