# Generated by Django 5.1.4 on 2026-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0046_logchecklistmanifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='qtd_coleta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qtd Coleta'),
        ),
    ]
