# Generated by Django 5.1.4 on 2026-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifesto', '0047_manifesto_qtd_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('CAVALO', 'Cavalo Mecânico'), ('CARRETA', 'Carreta'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('UTILITARIO', 'Utilitário'), ('OUTRO', 'Outro')], default='CAVALO', max_length=15, verbose_name='Tipo'),
        ),
    ]
