# Generated by Django 5.1.4 on 2026-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Vídeo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
                ('url_youtube', models.URLField(verbose_name='URL do YouTube (Não listado)')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Nº de Visualizações')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='👍 Gostei')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='👎 Não Gostei')),
                ('ativo', models.BooleanField(default=True, verbose_name='Vídeo Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
            ],
            options={
                'verbose_name': 'Vídeo de Treinamento',
                'verbose_name_plural': 'Central de Treinamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
