# Generated by Django 5.1.4 on 2026-09-03 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifesto', '0045_add_tipo_operacao_confirmado_webhook'),
        ('usuarios', '0030_alter_motorista_tipo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Última alteração por')),
                ('ocorrencias_pagamento_coleta', models.ManyToManyField(blank=True, help_text='Selecione os códigos de ocorrência onde o motorista compareceu ao local e deve ser remunerado pela coleta.', related_name='config_pagamento_coleta', to='manifesto.ocorrencia', verbose_name='Ocorrências que contam como Coleta Paga')),
                ('ocorrencias_pagamento_entrega', models.ManyToManyField(blank=True, help_text='Selecione os códigos de ocorrência onde o motorista compareceu ao local e deve ser remunerado pela entrega.', related_name='config_pagamento_entrega', to='manifesto.ocorrencia', verbose_name='Ocorrências que contam como Entrega Paga')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configuração Financeira',
            },
        ),
        migrations.CreateModel(
            name='DadosBancariosAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_bancarios', models.TextField(blank=True, help_text='Agência, Conta, Banco. Ex: AG:0001 C/C 12345-6 NUBANK', null=True, verbose_name='Dados Bancários')),
                ('chave_pix', models.CharField(blank=True, help_text='CPF, E-mail, Telefone ou Chave aleatória', max_length=200, null=True, verbose_name='Chave PIX')),
                ('titular_pagamento', models.CharField(blank=True, help_text='Nome do titular da conta bancária (se diferente do motorista)', max_length=200, null=True, verbose_name='Titular do Pagamento')),
                ('motorista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='usuarios.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Dados Bancários (Agregado)',
                'verbose_name_plural': 'Dados Bancários (Agregados)',
            },
        ),
        migrations.CreateModel(
            name='FechamentoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(verbose_name='Fim do Período')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('PAGO', 'Pago')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_finalizados', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por')),
            ],
            options={
                'verbose_name': 'Fechamento de Agregado',
                'verbose_name_plural': 'Fechamentos de Agregados',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo por dia rodado pelo motorista agregado.', max_digits=10, verbose_name='Valor da Diária (R$)')),
                ('valor_por_entrega', models.DecimalField(decimal_places=2, default=5.0, help_text='Valor pago por cada nota fiscal entregue com sucesso.', max_digits=10, verbose_name='Valor por Entrega (R$)')),
                ('valor_por_coleta', models.DecimalField(decimal_places=2, default=10.0, help_text='Valor pago por cada coleta válida realizada com sucesso.', max_digits=10, verbose_name='Valor por Coleta (R$)')),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.now, help_text='Data a partir da qual essa tarifa passa a valer.', verbose_name='Vigência a partir de')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_agregado', to='usuarios.filial', verbose_name='Filial / Base')),
            ],
            options={
                'verbose_name': 'Tarifa de Agregado',
                'verbose_name_plural': 'Tarifas de Agregados',
                'ordering': ['-vigencia_inicio', 'filial__nome'],
            },
        ),
        migrations.CreateModel(
            name='LinhaFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('qtd_entregas', models.IntegerField(default=0, verbose_name='Entregas Realizadas')),
                ('qtd_coletas', models.IntegerField(default=0, verbose_name='Nº de Coletas')),
                ('qtd_coletas_validas', models.IntegerField(default=0, verbose_name='Coletas Válidas')),
                ('qtd_ctes', models.IntegerField(default=0, verbose_name='Nº CT-es')),
                ('qtd_ctes_realizados', models.IntegerField(default=0, verbose_name='Nº CT-es Realizados')),
                ('total_embarques', models.IntegerField(default=0, verbose_name='Total Embarques')),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diária (R$)')),
                ('valor_entregas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Entregas (R$)')),
                ('valor_coletas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Coletas (R$)')),
                ('valor_extra', models.DecimalField(decimal_places=2, default=0, help_text='Valores adicionais por localidades especiais, etc.', max_digits=10, verbose_name='Valores Extras (R$)')),
                ('localidade_extra', models.CharField(blank=True, help_text='UF ou nome da localidade referente ao valor extra (ex: RJ, SP)', max_length=50, null=True, verbose_name='Localidade do Extra')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('total_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total do Dia (R$)')),
                ('breakdown_bases', models.JSONField(blank=True, default=dict, help_text='Contagem de entregas e coletas separadas por UF da filial de operação.', verbose_name='Detalhamento por Base')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='financeiro.fechamentoagregado', verbose_name='Fechamento')),
                ('filial_operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.filial', verbose_name='Base de Operação')),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_fechamento', to='manifesto.manifesto', verbose_name='Manifesto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_fechamento', to='usuarios.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Linha de Fechamento',
                'verbose_name_plural': 'Linhas de Fechamento',
                'ordering': ['motorista__nome_completo', 'data'],
                'unique_together': {('fechamento', 'manifesto')},
            },
        ),
        migrations.CreateModel(
            name='ResumoMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diarias', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Diárias (R$)')),
                ('total_servicos', models.IntegerField(default=0, verbose_name='Total Serviços')),
                ('diaria_por_servico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diária/Serviço (R$)')),
                ('total_parcial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Parcial (R$)')),
                ('valor_pedagio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Pedágio (R$)')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Valor de desconto (informar como negativo ou positivo, será subtraído).', max_digits=10, verbose_name='Descontos (R$)')),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Final (R$)')),
                ('breakdown_bases', models.JSONField(blank=True, default=dict, verbose_name='Totais por Base')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação Geral')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos', to='financeiro.fechamentoagregado', verbose_name='Fechamento')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_fechamento', to='usuarios.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Resumo por Motorista',
                'verbose_name_plural': 'Resumos por Motorista',
                'unique_together': {('fechamento', 'motorista')},
            },
        ),
    ]
