# Generated by Django 5.1.4 on 2026-09-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('usuarios', '0030_alter_motorista_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBasePagadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Cliente / Pagador')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ / CPF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('filial_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_financeiro', to='usuarios.filial', verbose_name='Filial Pagadora Responsável')),
            ],
            options={
                'verbose_name': 'Cliente / Base Pagadora',
                'verbose_name_plural': 'Clientes / Bases Pagadoras',
                'ordering': ['nome'],
            },
        ),
    ]
