# Generated by Django 4.2.29 on 2026-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_analytics', models.CharField(blank=True, default='', help_text='Token para endpoints de Analytics e Data Export da ESL', max_length=200, verbose_name='Token Analytics / Data Export')),
                ('token_graphql', models.CharField(blank=True, default='', help_text='Token para endpoints GraphQL e Invoice Occurrences da ESL', max_length=200, verbose_name='Token GraphQL / Invoices')),
                ('dominio_esl', models.CharField(default='quickdelivery.eslcloud.com.br', help_text='Ex: quickdelivery.eslcloud.com.br', max_length=200, verbose_name='Domínio ESL')),
                ('report_validacao', models.CharField(default='2972', help_text='ID do report de validação de manifestos', max_length=20, verbose_name='ID Report Validação')),
                ('report_busca_nfe', models.CharField(default='9873', help_text='ID do report de busca de notas fiscais', max_length=20, verbose_name='ID Report Busca NF-e')),
                ('processar_yolo', models.BooleanField(default=True, help_text='Se desligado, a foto vai direto para o TMS sem recorte da IA', verbose_name='🤖 Processar YOLO (Recorte de Canhoto)')),
                ('processar_ocr', models.BooleanField(default=True, help_text='Se desligado, a IA não tenta ler nem girar o canhoto', verbose_name='📖 Processar OCR (Leitura/Rotação)')),
                ('enviar_tms', models.BooleanField(default=False, help_text='Se desligado, as baixas são salvas no app mas NÃO enviadas ao TMS. Ideal para ambiente de desenvolvimento.', verbose_name='📤 Enviar para TMS (Integração ESL)')),
                ('enviar_email_falhas', models.BooleanField(default=False, help_text='Se ligado, envia e-mail quando uma integração com TMS falhar', verbose_name='📧 Enviar E-mail de Falhas')),
                ('armazenar_foto_backup', models.BooleanField(default=True, help_text='Se desligado, não salva a foto original no campo comprovante_original_url', verbose_name='💾 Armazenar Foto Original (Backup)')),
                ('codigos_ocorrencia_yolo', models.CharField(default='01,02,1,2', help_text='Códigos de ocorrência TMS separados por vírgula que passam pelo Agente IA (ex: 01,02,1,2)', max_length=100, verbose_name='Códigos que ativam YOLO')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
