# Generated by Django 4.2.29 on 2026-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='token_graphql',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='token_invoices',
            field=models.CharField(blank=True, default='', help_text='Token para endpoints de Invoice Occurrences, Freights e Picks da ESL (jz...LA)', max_length=200, verbose_name='Token Invoices / Ocorrências'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='token_analytics',
            field=models.CharField(blank=True, default='', help_text='Token para endpoints de Analytics, Data Export e GraphQL da ESL (zy...kw)', max_length=200, verbose_name='Token Data Export / GraphQL'),
        ),
    ]
