# Generated by Django 4.2.29 on 2026-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_remove_configuracaosistema_token_graphql_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='emails_notificacao',
            field=models.TextField(blank=True, default='', help_text='E-mails que vão receber as notificações de falha. Separe múltiplos e-mails por vírgula. Ex: cliente@empresa.com, gestor@empresa.com', verbose_name='📨 E-mails para Notificações'),
        ),
    ]
