# Generated by Django 4.2.29 on 2026-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_configuracaosistema_emails_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_api_url',
            field=models.URLField(blank=True, default='https://api.evolution.com.br', help_text='URL base da sua instância Evolution API', verbose_name='URL da Evolution API'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_instance',
            field=models.CharField(blank=True, default='instancia_wa', help_text='Nome da instância configurada na Evolution API', max_length=100, verbose_name='Nome da Instância WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_token',
            field=models.CharField(blank=True, default='', help_text='Token de autenticação (API Key)', max_length=200, verbose_name='Token Global/Instância WhatsApp'),
        ),
    ]
