# Generated by Django 4.2.27 on 2026-03-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0004_configuracaosistema_whatsapp_api_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='whatsapp_api_url',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='whatsapp_instance',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='whatsapp_token',
        ),
    ]
