# Generated by Django 4.2.27 on 2026-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_remove_configuracaosistema_whatsapp_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='habilitar_chat_sac',
            field=models.BooleanField(default=False, help_text='Se ligado, o ícone de chat flutuante será visível para os motoristas no app Mobile.', verbose_name='💬 Habilitar Chat SAC (App)'),
        ),
    ]
