# Generated by Django 5.1.4 on 2026-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0006_configuracaosistema_habilitar_chat_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='report_coletas',
            field=models.CharField(default='11324', help_text='ID do report de busca de coletas', max_length=20, verbose_name='ID Report Busca Coletas'),
        ),
    ]
