# Generated by Django 4.2.30 on 2026-06-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0007_configuracaosistema_report_coletas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='tms_config',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros de configuração extras específicos para o TMS (ex: tokens secundários, credenciais, etc).', verbose_name='⚙️ Configuração JSON do TMS'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='tms_provider',
            field=models.CharField(choices=[('esl_cloud', 'ESL Cloud'), ('totvs', 'TOTVS'), ('sap_tm', 'SAP TM'), ('intelipost', 'Intelipost'), ('nenhum', 'Sem integração TMS')], default='esl_cloud', help_text='Define qual sistema TMS este cliente usa para integração de manifestos.', max_length=30, verbose_name='🔗 Provedor TMS'),
        ),
    ]
