# Generated by Django 4.2.30 on 2026-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0008_configuracaosistema_tms_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='grupos_relatorio_whatsapp',
            field=models.TextField(blank=True, default='', help_text='Lista de JIDs dos grupos de WhatsApp separados por vírgula que receberão o relatório 22h.', verbose_name='Grupos para Relatório Diário'),
        ),
    ]
