# Generated by Django 5.1.4 on 2026-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0009_configuracaosistema_grupos_relatorio_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='modulo_torre_erros',
            field=models.BooleanField(default=False, help_text='Se desativado, a Torre de Erros não aparece no menu e nenhum log é gerado.', verbose_name='🚨 Módulo Torre de Controle de Erros'),
        ),
    ]
