# Generated by Django 5.1.4 on 2026-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0010_configuracaosistema_modulo_torre_erros'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='modulo_cargas_fretes',
            field=models.BooleanField(default=True, help_text='Se desativado, o painel de Cargas / Fretes por Remetente e Motorista é ocultado.', verbose_name='📦 Módulo Cargas & Fretes (SAC)'),
        ),
    ]
