# Generated by Django 5.1.4 on 2026-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0015_configuracaosistema_checklist_qvx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='checklist_qvx_url',
            field=models.CharField(default='https://checklist.qvx.com.br/api/webhooks/manifesto', help_text='Endpoint para onde o manifesto será enviado (POST)', max_length=300, verbose_name='URL da API do Checklist'),
        ),
    ]
