# Generated by Django 4.2.29 on 2026-03-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifesto', '0023_baixanf_payload_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoCanhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('confianca_yolo', models.FloatField(blank=True, null=True)),
                ('teve_sucesso', models.BooleanField(default=False)),
                ('foi_para_treino', models.BooleanField(default=False, help_text='Marcar se esta imagem de falha foi usada para melhorar o modelo')),
                ('observacao_erro', models.TextField(blank=True, null=True)),
                ('foto_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processamento_ia', to='manifesto.baixanf')),
            ],
            options={
                'verbose_name': 'Processamento de IA',
                'verbose_name_plural': 'Processamentos de IA',
            },
        ),
    ]
