# Generated by Django 4.2.27 on 2025-12-06 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CNH')),
                ('tipo_usuario', models.CharField(choices=[('MOTORISTA', 'Motorista'), ('OPERACIONAL', 'Operacional')], default='MOTORISTA', max_length=15, verbose_name='Tipo de Usuário')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='motoristas/fotos/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Conta de Usuário')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
    ]
