# Generated by Django 4.2.28 on 2026-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='id_filial_tms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
