# Generated by Django 4.2.27 on 2026-03-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_filial_id_filial_tms'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='usuarios.filial', verbose_name='Filial de Vínculo'),
        ),
    ]
