# Generated by Django 4.2.29 on 2026-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_motorista_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='ultima_bateria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Última Bateria (%)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso'),
        ),
    ]
