# Generated by Django 4.2.29 on 2026-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_motorista_ultima_bateria_motorista_ultimo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='ultima_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Última Latitude'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='ultima_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Última Longitude'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='ultima_rede',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Rede'),
        ),
    ]
