# Generated by Django 4.2.27 on 2026-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_motorista_ultima_lat_motorista_ultima_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cargo',
            field=models.CharField(choices=[('MEMBRO', 'Membro'), ('GERENTE', 'Gerente'), ('GESTOR', 'Gestor')], default='MEMBRO', max_length=10, verbose_name='Cargo'),
        ),
    ]
