# Generated by Django 4.2.27 on 2026-03-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_motorista_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='tipo_usuario',
            field=models.CharField(choices=[('MOTORISTA', 'Motorista'), ('OPERACIONAL', 'Operacional'), ('SAC', 'Suporte / SAC')], default='MOTORISTA', max_length=15, verbose_name='Tipo de Usuário'),
        ),
        migrations.CreateModel(
            name='PreCadastroSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF (Apenas números)')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('is_gestor', models.BooleanField(default=False, verbose_name='Visão Global (Gestor)?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Cadastro Ativo?')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sac_cadastrados', to='usuarios.filial', verbose_name='Filial Responsável')),
            ],
            options={
                'verbose_name': 'Pré-Cadastro SAC',
                'verbose_name_plural': 'Pré-Cadastros SAC',
            },
        ),
    ]
