# Generated by Django 4.2.29 on 2026-03-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_motorista_tipo_usuario_precadastrosac'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_acessar_dashboard', models.BooleanField(default=True, verbose_name='Acessar Dashboard')),
                ('pode_puxar_relatorio', models.BooleanField(default=False, verbose_name='Puxar Relatorios')),
                ('pode_ver_manifestos', models.BooleanField(default=True, verbose_name='Visualizar Manifestos')),
                ('pode_criar_manifesto', models.BooleanField(default=False, verbose_name='Criar Manifestos')),
                ('pode_excluir_manifesto', models.BooleanField(default=False, verbose_name='Excluir Manifestos')),
                ('pode_editar_manifesto', models.BooleanField(default=False, verbose_name='Editar Manifestos')),
                ('pode_adicionar_notas', models.BooleanField(default=True, verbose_name='Adicionar Notas ao Manifesto')),
                ('pode_remover_notas', models.BooleanField(default=False, verbose_name='Remover Notas do Manifesto')),
                ('pode_acessar_sac', models.BooleanField(default=False, verbose_name='Acessar Painel SAC')),
                ('pode_acessar_tickets', models.BooleanField(default=True, verbose_name='Acessar Tickets de Suporte')),
                ('pode_registrar_motorista', models.BooleanField(default=False, verbose_name='Registrar Motoristas')),
                ('pode_excluir_motorista', models.BooleanField(default=False, verbose_name='Excluir Motoristas')),
                ('pode_gerenciar_usuarios', models.BooleanField(default=False, verbose_name='Gerenciar Usuarios')),
                ('pode_alterar_permissoes', models.BooleanField(default=False, verbose_name='Alterar Permissoes de Usuarios')),
                ('pode_realizar_baixas', models.BooleanField(default=True, verbose_name='Realizar Baixas')),
                ('pode_ver_historico', models.BooleanField(default=True, verbose_name='Ver Historico de Baixas')),
                ('motorista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='usuarios.motorista', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permissao de Usuario',
                'verbose_name_plural': 'Permissoes de Usuarios',
            },
        ),
    ]
