# Generated by Django 4.2.30 on 2026-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_permissaousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='is_sac_mobile',
            field=models.BooleanField(default=False, verbose_name='Acesso App SAC'),
        ),
    ]
