# Generated by Django 4.2.30 on 2026-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_motorista_is_sac_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / Celular'),
        ),
    ]
