# Generated by Django 5.1.4 on 2026-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_motorista_is_sac_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / Celular'),
        ),
        migrations.AddField(
            model_name='precadastrosac',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Obrigatório para o envio do link de convite.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cargo',
            field=models.CharField(choices=[('MEMBRO', 'Membro'), ('GERENTE', 'Gerente'), ('GESTOR', 'Gestor'), ('ADMINISTRADOR', 'Administrador')], default='MEMBRO', max_length=15, verbose_name='Cargo'),
        ),
    ]
