# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_motorista_email_motorista_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='permitir_upload_galeria',
            field=models.BooleanField(default=False, help_text='Se marcado, remove a trava da câmera nativa e permite que o motorista escolha fotos da galeria em vez de forçar a abertura da câmera (Evita travamento e recarregamento da página em celulares com pouca memória).', verbose_name='Permitir Upload da Galeria (Celular Fraco)'),
        ),
    ]
