# Generated by Django 4.2.30 on 2026-06-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_motorista_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='precadastrosac',
            name='email',
            field=models.EmailField(default='', help_text='Obrigatório para o envio do link de convite.', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
