# Generated by Django 4.2.30 on 2026-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_motorista_email_precadastrosac_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastrosac',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Obrigatório para o envio do link de convite.', max_length=254, verbose_name='E-mail'),
        ),
    ]
