# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_motorista_permitir_upload_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='modelo_aparelho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Aparelho'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Memória RAM'),
        ),
    ]
