# Generated by Django 4.2.30 on 2026-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_precadastrosac_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cargo',
            field=models.CharField(choices=[('MEMBRO', 'Membro'), ('GERENTE', 'Gerente'), ('GESTOR', 'Gestor'), ('ADMINISTRADOR', 'Administrador')], default='MEMBRO', max_length=15, verbose_name='Cargo'),
        ),
    ]
