# Generated by Django 4.2.30 on 2026-06-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_motorista_email_motorista_telefone_and_more'),
        ('usuarios', '0015_alter_motorista_cargo'),
    ]

    operations = [
    ]
