# Generated by Django 4.2.30 on 2026-07-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_motorista_permitir_upload_galeria'),
        ('usuarios', '0016_merge_20260615_1752'),
    ]

    operations = [
    ]
