# Generated by Django 4.2.30 on 2026-07-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_motorista_modelo_aparelho_motorista_memoria_ram'),
        ('usuarios', '0017_merge_20260702_1534'),
    ]

    operations = [
    ]
