# Generated by Django 4.2.30 on 2026-07-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_merge_20260702_1603'),
        ('usuarios', '0020_alter_devicetoken_id_alter_devicetoken_ultimo_uso_and_more'),
    ]

    operations = [
    ]
