# Generated by Django 4.2.30 on 2026-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_devicetoken_id_alter_devicetoken_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='categoria',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('AGREGADO', 'Agregado'), ('DEDICADO', 'Dedicado')], default='EMPRESA', max_length=20, verbose_name='Categoria do Motorista'),
        ),
    ]
