# Generated by Django 5.1.4 on 2026-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_motorista_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='horario_rebusca_esl',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Rebusca Automática (ESL)'),
        ),
    ]
