# Generated by Django 4.2.30 on 2026-07-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_merge_20260714_1309'),
        ('usuarios', '0021_motorista_categoria'),
    ]

    operations = [
    ]
