# Generated by Django 4.2.30 on 2026-07-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_filial_horario_rebusca_esl'),
        ('usuarios', '0022_merge_20260715_1402'),
    ]

    operations = [
    ]
