# Generated by Django 5.1.4 on 2026-07-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_filial_horario_rebusca_esl'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token Firebase FCM'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='fcm_token_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização FCM'),
        ),
        migrations.CreateModel(
            name='NotificacaoPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('SISTEMA', 'Aviso do Sistema'), ('LEMBRETE', 'Lembrete de Routine / GPS'), ('MANIFESTO', 'Atualização de Manifesto'), ('ALERTA', 'Alerta Operacional'), ('MANUAL', 'Disparo Manual Admin')], default='SISTEMA', max_length=20, verbose_name='Tipo')),
                ('dados_payload', models.JSONField(blank=True, null=True, verbose_name='Dados Extras (JSON)')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Enviado com Sucesso')),
                ('response_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Resposta Firebase')),
                ('erro_detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes de Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado / Enviado em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_notificacoes_push', to='usuarios.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Log de Notificação Push',
                'verbose_name_plural': 'Logs de Notificações Push',
                'ordering': ['-criado_em'],
            },
        ),
    ]
