# Generated by Django 4.2.30 on 2026-07-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_merge_20260721_1521'),
        ('usuarios', '0023_motorista_fcm_token_and_more'),
    ]

    operations = [
    ]
