# Generated by Django 5.1.4 on 2026-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_motorista_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='whatsapp_operacional',
            field=models.CharField(blank=True, help_text='Número do WhatsApp do operacional da filial. Informe a partir do DDD (ex: 21999999999).', max_length=20, null=True, verbose_name='WhatsApp Operacional'),
        ),
        migrations.AddField(
            model_name='filial',
            name='whatsapp_sac',
            field=models.CharField(blank=True, help_text='Número do WhatsApp do SAC da filial. Informe a partir do DDD (ex: 21999999999).', max_length=20, null=True, verbose_name='WhatsApp SAC'),
        ),
    ]
