# Generated by Django 5.1.4 on 2026-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_add_tipo_operacao_confirmado_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='tipo_usuario',
            field=models.CharField(choices=[('MOTORISTA', 'Motorista'), ('OPERACIONAL', 'Operacional'), ('SAC', 'Suporte / SAC'), ('FINANCEIRO', 'Financeiro')], default='MOTORISTA', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
