# Generated by Django on 2026-09-17

from django.db import migrations
from django.db.models import Q


def merge_filial_sp_duplicada(apps, schema_editor):
    Filial = apps.get_model('usuarios', 'Filial')
    Manifesto = apps.get_model('manifesto', 'Manifesto')
    Motorista = apps.get_model('usuarios', 'Motorista')

    sp_oficial = Filial.objects.filter(nome__iexact='QUICK SAO PAULO').first()
    if not sp_oficial:
        sp_oficial = Filial.objects.filter(id_filial_tms='237978').first()

    if sp_oficial:
        campos = []
        if sp_oficial.id_filial_tms != '237978':
            sp_oficial.id_filial_tms = '237978'
            campos.append('id_filial_tms')
        if not sp_oficial.cnpj or '14539546000120' not in sp_oficial.cnpj:
            sp_oficial.cnpj = '14539546000120'
            campos.append('cnpj')
        if not sp_oficial.operacao_ativa:
            sp_oficial.operacao_ativa = True
            campos.append('operacao_ativa')
        if campos:
            sp_oficial.save(update_fields=campos)

        dups = Filial.objects.filter(
            Q(nome__icontains='QUICK DELIVERY SAO PAULO') | Q(id_filial_tms='14539546000120')
        ).exclude(id=sp_oficial.id)

        for d in dups:
            Manifesto.objects.filter(filial=d).update(filial=sp_oficial)
            Manifesto.objects.filter(filial_operacao=d).update(filial_operacao=sp_oficial)
            Motorista.objects.filter(filial=d).update(filial=sp_oficial)
            d.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_motorista_modo_camera'),
        ('manifesto', '0046_logchecklistmanifesto'),
    ]

    operations = [
        migrations.RunPython(merge_filial_sp_duplicada, migrations.RunPython.noop),
    ]
