# Generated by Django 5.1.4 on 2026-07-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExclusaoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, help_text='Salvo como texto para manter registro mesmo se o usuário for excluído', max_length=255, verbose_name='Nome do Operador')),
                ('nota_fiscal_id', models.IntegerField(verbose_name='ID da Nota Fiscal')),
                ('nota_fiscal_numero', models.CharField(max_length=20, verbose_name='Número NF')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('manifesto_numero', models.CharField(max_length=50, verbose_name='Nº Manifesto')),
                ('motorista_nome', models.CharField(blank=True, max_length=255, verbose_name='Motorista')),
                ('ocorrencia_codigo', models.CharField(blank=True, max_length=30, verbose_name='Código Ocorrência TMS')),
                ('ocorrencia_descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição Ocorrência')),
                ('tipo_baixa', models.CharField(blank=True, max_length=20, verbose_name='Tipo da Baixa')),
                ('estava_integrado_tms', models.BooleanField(default=False, verbose_name='Estava integrado no TMS?')),
                ('motivo_exclusao', models.TextField(verbose_name='Motivo da Exclusão')),
                ('dados_baixa_json', models.JSONField(blank=True, help_text='JSON com todos os campos do registro de BaixaNF antes da exclusão', null=True, verbose_name='Dados Completos da Baixa (Backup)')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Exclusão')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador que excluiu')),
            ],
            options={
                'verbose_name': 'Log de Exclusão de Ocorrência',
                'verbose_name_plural': 'Logs de Exclusão de Ocorrências',
                'ordering': ['-data_exclusao'],
            },
        ),
    ]
